/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as ProtectedProfilRouteImport } from './routes/_protected/profil'
import { Route as ProtectedObjectifsRouteImport } from './routes/_protected/objectifs'
import { Route as ProtectedMichelRouteImport } from './routes/_protected/michel'
import { Route as ProtectedDocsRouteImport } from './routes/_protected/docs'
import { Route as ProtectedCandidaturesRouteImport } from './routes/_protected/candidatures'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfilRoute = ProtectedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedObjectifsRoute = ProtectedObjectifsRouteImport.update({
  id: '/objectifs',
  path: '/objectifs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMichelRoute = ProtectedMichelRouteImport.update({
  id: '/michel',
  path: '/michel',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDocsRoute = ProtectedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCandidaturesRoute = ProtectedCandidaturesRouteImport.update({
  id: '/candidatures',
  path: '/candidatures',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRoute
  '/candidatures': typeof ProtectedCandidaturesRoute
  '/docs': typeof ProtectedDocsRoute
  '/michel': typeof ProtectedMichelRoute
  '/objectifs': typeof ProtectedObjectifsRoute
  '/profil': typeof ProtectedProfilRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRoute
  '/candidatures': typeof ProtectedCandidaturesRoute
  '/docs': typeof ProtectedDocsRoute
  '/michel': typeof ProtectedMichelRoute
  '/objectifs': typeof ProtectedObjectifsRoute
  '/profil': typeof ProtectedProfilRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof ProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_protected/candidatures': typeof ProtectedCandidaturesRoute
  '/_protected/docs': typeof ProtectedDocsRoute
  '/_protected/michel': typeof ProtectedMichelRoute
  '/_protected/objectifs': typeof ProtectedObjectifsRoute
  '/_protected/profil': typeof ProtectedProfilRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_protected/': typeof ProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/verify-email'
    | '/candidatures'
    | '/docs'
    | '/michel'
    | '/objectifs'
    | '/profil'
    | '/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/verify-email'
    | '/candidatures'
    | '/docs'
    | '/michel'
    | '/objectifs'
    | '/profil'
    | '/oauth/callback'
    | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/verify-email'
    | '/_protected/candidatures'
    | '/_protected/docs'
    | '/_protected/michel'
    | '/_protected/objectifs'
    | '/_protected/profil'
    | '/oauth/callback'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profil': {
      id: '/_protected/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProtectedProfilRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/objectifs': {
      id: '/_protected/objectifs'
      path: '/objectifs'
      fullPath: '/objectifs'
      preLoaderRoute: typeof ProtectedObjectifsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/michel': {
      id: '/_protected/michel'
      path: '/michel'
      fullPath: '/michel'
      preLoaderRoute: typeof ProtectedMichelRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/docs': {
      id: '/_protected/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof ProtectedDocsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/candidatures': {
      id: '/_protected/candidatures'
      path: '/candidatures'
      fullPath: '/candidatures'
      preLoaderRoute: typeof ProtectedCandidaturesRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedCandidaturesRoute: typeof ProtectedCandidaturesRoute
  ProtectedDocsRoute: typeof ProtectedDocsRoute
  ProtectedMichelRoute: typeof ProtectedMichelRoute
  ProtectedObjectifsRoute: typeof ProtectedObjectifsRoute
  ProtectedProfilRoute: typeof ProtectedProfilRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCandidaturesRoute: ProtectedCandidaturesRoute,
  ProtectedDocsRoute: ProtectedDocsRoute,
  ProtectedMichelRoute: ProtectedMichelRoute,
  ProtectedObjectifsRoute: ProtectedObjectifsRoute,
  ProtectedProfilRoute: ProtectedProfilRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
