/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedObjectivesRouteImport } from './routes/_protected/objectives'
import { Route as ProtectedDocumentsRouteImport } from './routes/_protected/documents'
import { Route as ProtectedApplicationsRouteImport } from './routes/_protected/applications'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedObjectivesRoute = ProtectedObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDocumentsRoute = ProtectedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedApplicationsRoute = ProtectedApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof ProtectedAdminRoute
  '/applications': typeof ProtectedApplicationsRoute
  '/documents': typeof ProtectedDocumentsRoute
  '/objectives': typeof ProtectedObjectivesRoute
  '/profile': typeof ProtectedProfileRoute
  '/oauth/callback': typeof OauthCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof ProtectedAdminRoute
  '/applications': typeof ProtectedApplicationsRoute
  '/documents': typeof ProtectedDocumentsRoute
  '/objectives': typeof ProtectedObjectivesRoute
  '/profile': typeof ProtectedProfileRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/': typeof ProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/applications': typeof ProtectedApplicationsRoute
  '/_protected/documents': typeof ProtectedDocumentsRoute
  '/_protected/objectives': typeof ProtectedObjectivesRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_protected/': typeof ProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/applications'
    | '/documents'
    | '/objectives'
    | '/profile'
    | '/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/applications'
    | '/documents'
    | '/objectives'
    | '/profile'
    | '/oauth/callback'
    | '/'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/admin'
    | '/_protected/applications'
    | '/_protected/documents'
    | '/_protected/objectives'
    | '/_protected/profile'
    | '/oauth/callback'
    | '/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/objectives': {
      id: '/_protected/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ProtectedObjectivesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/documents': {
      id: '/_protected/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof ProtectedDocumentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/applications': {
      id: '/_protected/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ProtectedApplicationsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedApplicationsRoute: typeof ProtectedApplicationsRoute
  ProtectedDocumentsRoute: typeof ProtectedDocumentsRoute
  ProtectedObjectivesRoute: typeof ProtectedObjectivesRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedApplicationsRoute: ProtectedApplicationsRoute,
  ProtectedDocumentsRoute: ProtectedDocumentsRoute,
  ProtectedObjectivesRoute: ProtectedObjectivesRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
